# Generated by Django 3.0 on 2020-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingUser',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
            ],
        ),
    ]
